-- 코드를 작성해주세요

# WITH RECURSIVE t AS (
#     SELECT ID, PARENT_ID
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NULL
    
#     UNION ALL
    
#     SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID
#     FROM ECOLI_DATA
#     JOIN t ON t.ID = ECOLI_DATA.PARENT_ID
# )

# SELECT COUNT(*)
# FROM t
# GROUP BY PARENT_ID;

# SELECT *
# FROM t;


SELECT p.ID, COUNT(c.ID) CHILD_COUNT
FROM ECOLI_DATA p
LEFT JOIN ECOLI_DATA c
ON c.PARENT_ID = p.ID
GROUP BY p.ID
ORDER BY p.ID;
