WITH ECOLI_CLASSIFIED AS (
    SELECT
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS NTILE_RANK
    FROM ECOLI_DATA
)

SELECT
    ID,
    CASE NTILE_RANK
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        WHEN 4 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_CLASSIFIED
ORDER BY ID ASC;