# -- 코드를 입력하세요
# # SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
# # FROM ANIMAL_INS AS i
# # JOIN ANIMAL_OUTS AS o
# # ON i.ANIMAL_ID = o.ANIMAL_ID
# # WHERE i.SEX_UPON_INTAKE LIKE 'Intact%'AND o.ANIMAL_ID IN (
# #     SELECT ANIMAL_ID
# #     FROM ANIMAL_OUTS
# #     WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%')
# # ORDER BY i.ANIMAL_ID;

# SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
# FROM ANIMAL_INS AS i
# JOIN ANIMAL_OUTS AS o
# ON i.ANIMAL_ID = o.ANIMAL_ID
# WHERE i.SEX_UPON_INTAKE LIKE 'Intact%' AND (o.SEX_UPON_OUTCOME LIKE 'Spayed%' OR o.SEX_UPON_OUTCOME LIKE 'Neutered%')
# ORDER BY i.ANIMAL_ID;


SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i
JOIN ANIMAL_OUTS O ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE (i.SEX_UPON_INTAKE LIKE 'Intact%') AND (
    o.SEX_UPON_OUTCOME LIKE'Spayed%' OR o.SEX_UPON_OUTCOME LIKE'Neutered%'
)
ORDER BY i.ANIMAL_ID;






