WITH RECURSIVE GENERATION_TABLE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION -- anchor
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GENERATION_TABLE g ON e.parent_id = g.id
)

SELECT COUNT(*) AS COUNT, g.generation AS GENERATION
FROM GENERATION_TABLE g
LEFT JOIN ECOLI_DATA c ON g.id = c.parent_id
WHERE c.id IS NULL
GROUP BY g.generation
ORDER BY g.generation;