SELECT h.HISTORY_ID,
    TRUNCATE( c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) * (
        1 - IFNULL(
            CASE
                WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 90 THEN D90.DISCOUNT_RATE / 100
                WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 30 THEN D30.DISCOUNT_RATE / 100
                WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 7 THEN D7.DISCOUNT_RATE / 100
                ELSE 0
            END, 0)
    ), 0) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
JOIN CAR_RENTAL_COMPANY_CAR c
ON h.CAR_ID = c.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D90
ON c.CAR_TYPE = D90.CAR_TYPE AND D90.DURATION_TYPE = '90일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D30
ON c.CAR_TYPE = D30.CAR_TYPE AND D30.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D7
ON c.CAR_TYPE = D7.CAR_TYPE AND D7.DURATION_TYPE = '7일 이상'
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;


