-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
WITH BIGGEST AS (
    SELECT MAX(cnt.COUNT) MAX_CNT
    FROM (
        SELECT r.MEMBER_ID, COUNT(r.MEMBER_ID) COUNT
        FROM REST_REVIEW r
        GROUP BY r.MEMBER_ID
    ) cnt
)

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM REST_REVIEW r
JOIN MEMBER_PROFILE m
ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID IN (
    SELECT rr.MEMBER_ID
    FROM REST_REVIEW rr
    GROUP BY rr.MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(cnt.COUNT) MAX_CNT
        FROM (
            SELECT r.MEMBER_ID, COUNT(r.MEMBER_ID) COUNT
            FROM REST_REVIEW r
            GROUP BY r.MEMBER_ID
        ) cnt
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;


# (SELECT cnt.MEMBER_ID, MAX(cnt.COUNT)
# FROM (SELECT r.MEMBER_ID, COUNT(r.MEMBER_ID) COUNT
# FROM REST_REVIEW r
# GROUP BY r.MEMBER_ID) cnt);

