SELECT
CASE
    WHEN SUM(CASE WHEN s.CATEGORY = 'Front End' THEN 1 END) > 0
        AND SUM(CASE WHEN s.NAME = 'Python' Then 1 END) > 0
    THEN 'A'
    WHEN SUM(CASE WHEN s.NAME = 'C#' Then 1 END) > 0
    THEN 'B'
    WHEN SUM(CASE WHEN s.CATEGORY = 'Front End' THEN 1 END) > 0
    THEN 'C'
END GRADE,
d.ID, d.EMAIL
FROM DEVELOPERS d
JOIN SKILLCODES s
ON (d.SKILL_CODE & s.CODE) = s.CODE
GROUP BY d.ID, d.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, d.ID;